import {Inter} from "next/font/google";
import {getDictionary} from './dictionaries';
import {I18nProvider} from './provider';

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export async function generateStaticParams() {
    return [{lang: 'en-us'}, {lang: 'es-es'}]
}

export default async function RootLayout({children, params: {lang}}) {
    console.log(lang)
    const locale = lang
    let messages = await getDictionary(locale)
    console.log(messages)
    return (
        <html lang="en">
            <body className={inter.className}>
                <I18nProvider locale={locale} messages={messages}>
                    {children}
                </I18nProvider>
            </body>
        </html>
    );
}
